"""Single registry of settings-table keys. Never inline these strings."""

GOOGLE_TOKENS = "google_tokens"
GOOGLE_CLIENT_ID = "google_client_id"
GOOGLE_CLIENT_SECRET = "google_client_secret"
SPREADSHEET_ID = "spreadsheet_id"
OCR_PROVIDER = "ocr_provider"
WHATSAPP_ALLOWED_SENDERS = "whatsapp_allowed_senders"
WHATSAPP_SUMMARY_CHAT = "whatsapp_summary_chat"
LAST_SYNC_ERROR = "last_sync_error"
ACTIVE_PROFILE = "active_profile"
GOOGLE_PKCE_VERIFIER = "google_pkce_verifier"
DRIVE_FOLDER_BASE_NAME = "drive_folder_base_name"
DRIVE_YEAR_FOLDERS = "drive_year_folders"
DRIVE_ROOT_FOLDER_ID = "drive_root_folder_id"
LAST_SYNC_AT = "last_sync_at"
LAST_SYNC_COUNT = "last_sync_count"
SHEET_COLUMN_CONFIG = "sheet_column_config"
GOOGLE_OAUTH_STATE = "google_oauth_state"
